// Background service worker

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'analyze_post') {
    handleAnalysis(request.text, request.imageSrc, request.username, request.context, sendResponse);
    return true; 
  }
  if (request.action === 'validate_connection') {
    handleValidation(request.apiKey, request.provider, request.model, sendResponse);
    return true; 
  }
});

async function handleAnalysis(text, imageSrc, username, context, sendResponse) {
  try {
    const data = await chrome.storage.local.get(['openai_api_key', 'ai_provider', 'ai_model']);
    const apiKey = data.openai_api_key;
    const provider = data.ai_provider || 'openai';
    const model = data.ai_model || ''; 

    if (!apiKey) {
      sendResponse({ error: 'API Key not found. Please set it in the extension popup.' });
      return;
    }

    // 1. Fetch image if exists
    let imageBase64 = null;
    let mimeType = null;
    if (imageSrc) {
      try {
        const imgData = await fetchImage(imageSrc);
        imageBase64 = imgData.base64;
        mimeType = imgData.mimeType;
      } catch (e) {
        console.warn('Failed to fetch image:', e);
      }
    }

    // 2. Call API
    let analysisResult;
    if (provider === 'gemini') {
      analysisResult = await callGemini(apiKey, text, imageBase64, mimeType, model, false, context);
    } else if (provider === 'anthropic') {
      analysisResult = await callClaude(apiKey, text, imageBase64, mimeType, model, false, context);
    } else {
      analysisResult = await callOpenAICompatible(apiKey, provider, text, imageBase64, mimeType, model, false, context);
    }

    // 3. Update Ranking Data
    await updateRanking(username, analysisResult);

    // 4. Return result
    sendResponse({ success: true, data: analysisResult });

  } catch (error) {
    console.error('Analysis error:', error);
    sendResponse({ error: error.message || 'An error occurred during analysis.' });
  }
}

async function fetchImage(url) {
  const response = await fetch(url);
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const dataUrl = reader.result;
      const base64 = dataUrl.split(',')[1];
      const mimeType = dataUrl.substring(dataUrl.indexOf(':') + 1, dataUrl.indexOf(';'));
      resolve({ base64, mimeType });
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

const SYSTEM_PROMPT = `
Analyze the following social media content (which may include an image).

YOUR TASK:
1. Determine if the content is factual or contains misinformation.
2. Estimate the probability (0-100) that this content was generated by an AI.

IMPORTANT: If "Original Post Context" is provided, use it to understand the context of the "Content to Analyze". 
Your rating and analysis must apply to the "Content to Analyze", not the context.

CALCULATION INSTRUCTIONS (CRITICAL):
You must derive the final "ai_probability" score by combining two factors with equal weight (50/50):
  A. Heuristic Score (0-100): Based strictly on the "AI DETECTION HEURISTICS" list below. If many heuristics match, this score is high. If few match, it is low.
  B. Model Intuition Score (0-100): Based on your own internal training. 
     - 0 means "Definitely Human" (e.g., highly emotional, chaotic, personal).
     - 100 means "Definitely AI" (e.g., synthetic, robotic).
     - DO NOT REVERSE THIS. A low score = Human. A high score = AI.
  
  FINAL SCORE = (Heuristic Score * 0.5) + (Model Intuition Score * 0.5)

AI DETECTION HEURISTICS (Factor A - Higher score = More likely AI):
- LANGUAGE INDEPENDENCE: It is OK if the text is not English. Validate if the username looks legitimate for the language used.
- PUNCTUATION: Check for overuse of specific punctuation like the em dash (—).
- STRUCTURE: Look for the "Sandwich" structure: Intro rephrasing prompt -> List/Bullets -> Generic "In conclusion" summary.
- BURSTINESS: AI writes in uniform sentence lengths and structures. Humans vary their sentence length significantly (burstiness). If sentences are very uniform, increase score.
- OVER-REPRESENTED WORDS: Be suspicious of words like: "Delve", "tapestry", "landscape", "testament", "orchestrate", "realm", "journey", "crucial", "essential", "foster", "transformative", "game-changer", "comprehensive", "robust", "synergy", "paradigm", "leverage", "optimize", "streamline", "innovative", "cutting-edge".
- VOICE: Look for a lack of "Voice" or strong opinion. AI often sounds neutral, corporate, and helpful. It rarely uses sarcasm, slang, or strong "I" statements.
- TYPOGRAPHY: Look for curly quotation marks (“ ”) and apostrophes (’) instead of straight ones, which can be an artifact of some AI formatters.
- FORMATTING: AI loves structured lists and bullet points. Heavy use of these in a casual social media setting is suspicious.
- SPELLING: If there are spelling mistakes, it is LIKELY HUMAN (decrease score significantly). AI rarely makes typos.
- IMAGES: If an image is present, check for artifacts, text rendering issues, or physics errors.

Return ONLY a valid JSON object with this structure:
{
  "is_factual": boolean,
  "fact_check_details": "string explaining the fact check result",
  "ai_probability": number,
  "ai_reasoning": "string explaining the breakdown: 'Heuristic Score: X, Model Intuition: Y. Final Score: Z. Reasoning: ...'",
  "overall_rating": "Truthful" | "Misleading" | "False" | "Satire" | "Opinion"
}
`;

async function callOpenAICompatible(apiKey, provider, text, imageBase64, mimeType, customModel, isValidation = false, context = null) {
  let url = 'https://api.openai.com/v1/chat/completions';
  let model = customModel || 'gpt-4o-mini';
  
  const headers = {
    'Content-Type': 'application/json',
    'Authorization': `Bearer ${apiKey}`
  };

  if (provider === 'openrouter') {
    url = 'https://openrouter.ai/api/v1/chat/completions';
    model = customModel || 'openai/gpt-4o-mini';
    headers['HTTP-Referer'] = 'https://github.com/vitaly/social-policy';
    headers['X-Title'] = 'Social Police Extension';
  }

  let messages;
  if (isValidation) {
    messages = [{ role: 'user', content: 'Hi' }];
  } else {
    const content = [];
    if (context) content.push({ type: "text", text: `Original Post Context: "${context}"` });
    if (text) content.push({ type: "text", text: `Content to Analyze: "${text}"` });
    if (imageBase64) {
      content.push({
        type: "image_url",
        image_url: {
          url: `data:${mimeType};base64,${imageBase64}`
        }
      });
    }
    messages = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: content }
    ];
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: headers,
    body: JSON.stringify({
      model: model,
      messages: messages,
      temperature: 0.1,
      max_tokens: isValidation ? 5 : undefined
    })
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error?.message || 'API request failed');
  }

  const result = await response.json();
  const contentStr = result.choices[0].message.content;
  if (isValidation) return contentStr;
  return parseJSONResponse(contentStr);
}

async function callGemini(apiKey, text, imageBase64, mimeType, customModel, isValidation = false, context = null) {
  const model = customModel || 'gemini-1.5-flash';
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  
  let parts = [];
  if (isValidation) {
    parts.push({ text: "Hi" });
  } else {
    let prompt = SYSTEM_PROMPT;
    if (context) prompt += `\n\nOriginal Post Context: "${context}"`;
    prompt += `\n\nContent to Analyze: "${text || '[No text]'}"`;
    parts.push({ text: prompt });

    if (imageBase64) {
      parts.push({
        inlineData: {
          mimeType: mimeType,
          data: imageBase64
        }
      });
    }
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: parts }],
      generationConfig: {
        responseMimeType: isValidation ? undefined : "application/json",
        maxOutputTokens: isValidation ? 5 : undefined
      }
    })
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error?.message || 'Gemini API request failed');
  }

  const result = await response.json();
  const content = result.candidates[0].content.parts[0].text;
  if (isValidation) return content;
  return parseJSONResponse(content);
}

async function callClaude(apiKey, text, imageBase64, mimeType, customModel, isValidation = false, context = null) {
  const url = 'https://api.anthropic.com/v1/messages';
  const model = customModel || 'claude-3-5-sonnet-20240620';
  
  let messages = [];
  if (isValidation) {
    messages.push({ role: 'user', content: "Hi" });
  } else {
    const content = [];
    if (imageBase64) {
      content.push({
        type: "image",
        source: {
          type: "base64",
          media_type: mimeType,
          data: imageBase64
        }
      });
    }
    if (context) {
      content.push({ type: "text", text: `Original Post Context: "${context}"` });
    }
    if (text) {
      content.push({ type: "text", text: `Content to Analyze: "${text}"` });
    } else if (!imageBase64) {
      content.push({ type: "text", text: "Empty post." });
    }
    
    messages.push({ role: 'user', content: content });
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
      'anthropic-dangerous-direct-browser-access': 'true'
    },
    body: JSON.stringify({
      model: model,
      max_tokens: isValidation ? 5 : 1024,
      system: isValidation ? undefined : SYSTEM_PROMPT,
      messages: messages
    })
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.error?.message || 'Claude API request failed');
  }

  const result = await response.json();
  const contentStr = result.content[0].text;
  if (isValidation) return contentStr;
  return parseJSONResponse(contentStr);
}

function parseJSONResponse(content) {
  // 1. Try to parse strictly first (after basic cleanup)
  let cleaned = content.replace(/```json\n?|```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    // 2. If that fails, try to extract the first JSON object using regex
    const match = content.match(/\{[\s\S]*\}/);
    if (match) {
      try {
        return JSON.parse(match[0]);
      } catch (e2) {
        // Failed again
      }
    }
    console.error("Failed to parse JSON. Raw content:", content);
    throw new Error("Failed to parse AI response as JSON. Received: " + content.substring(0, 50) + "...");
  }
}

// Handler for validation
async function handleValidation(apiKey, provider, model, sendResponse) {
  try {
    if (provider === 'gemini') {
      await callGemini(apiKey, "Hello", null, null, model, true);
    } else if (provider === 'anthropic') {
      await callClaude(apiKey, "Hello", null, null, model, true);
    } else {
      await callOpenAICompatible(apiKey, provider, "Hello", null, null, model, true);
    }
    sendResponse({ success: true });
  } catch (error) {
    sendResponse({ success: false, error: error.message });
  }
}

async function updateRanking(username, result) {
  const storage = await chrome.storage.local.get(['rankings']);
  const rankings = storage.rankings || {};

  if (!rankings[username]) {
    rankings[username] = {
      username: username,
      checked_posts: 0,
      ai_posts: 0, 
      misinformation_posts: 0,
      history: []
    };
  }

  const userStats = rankings[username];
  userStats.checked_posts += 1;
  
  if (result.ai_probability > 50) {
    userStats.ai_posts += 1;
  }
  
  if (result.is_factual === false || result.overall_rating === 'False' || result.overall_rating === 'Misleading') {
    userStats.misinformation_posts += 1;
  }

  userStats.history.push({
    date: new Date().toISOString(),
    result: result
  });

  await chrome.storage.local.set({ rankings });
}
